services:
  # Grafana - Visualisation et dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: thirdshop-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - observability
    depends_on:
      - prometheus
      - loki
      - tempo

  # Prometheus - Métriques et monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: thirdshop-prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--enable-feature=exemplar-storage'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - observability

  # Tempo - Distributed tracing
  tempo:
    image: grafana/tempo:latest
    container_name: thirdshop-tempo
    ports:
      - "3200:3200"   # tempo
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    networks:
      - observability

  # Loki - Agrégation de logs
  loki:
    image: grafana/loki:latest
    container_name: thirdshop-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - observability

  # Promtail - Agent pour collecter les logs et les envoyer à Loki
  promtail:
    image: grafana/promtail:latest
    container_name: thirdshop-promtail
    volumes:
      - ./loki/promtail.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - ./logs:/logs:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - observability
    depends_on:
      - loki

volumes:
  grafana-data:
  prometheus-data:
  tempo-data:
  loki-data:

networks:
  observability:
    driver: bridge
